repos:
  - hooks:
      - id: sync-rye-pre-commit
        args:
          - "-a ruff:ruff:v:"
          - "-a ruff:ruff-format:v:"
          - "-a mypy:mypy:v:"
    repo: https://github.com/phi-friday/sync-rye-pre-commit
    rev: v0.1.5

  - hooks:
      - id: ruff
        name: ruff-lint
      - id: ruff-format
        name: ruff-format
        args: [--check]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7

  - hooks:
      - id: mypy
        name: mypy
        args: [--strict]
        additional_dependencies: [django]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1

  - hooks:
      - id: pyright
        name: pyright
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.375