repos:
  - hooks:
      - id: ruff
        name: ruff-lint
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4

  - hooks:
      - id: ruff-format
        name: ruff-format
        args: [--check]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4