repos:
  - hooks:
      - id: ruff
        name: ruff-lint
      - id: ruff-format
        name: ruff-format
        args: [--check]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7

  - hooks:
      - id: mypy
        name: mypy
        args: [--strict]
        additional_dependencies: [django]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1

  - hooks:
      - id: pyright
        name: pyright
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.375